Fatal Python error: Segmentation fault

Thread 0x000015010233fb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015010550bb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x0000150108b78b30 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/scapy/supersocket.py", line 259 in select
  File "/usr/local/lib/python3.9/site-packages/scapy/sendrecv.py", line 1175 in _run
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015010d07fb30 (most recent call first):
  File "/usr/local/lib/python3.9/selectors.py", line 469 in select
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1854 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596 in run_forever
  File "/usr/local/lib/python3.9/site-packages/bellows/thread.py", line 28 in _thread_main
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52 in run
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015010e7fdb30 (most recent call first):
  File "/usr/local/lib/python3.9/threading.py", line 316 in wait
  File "/usr/local/lib/python3.9/queue.py", line 180 in get
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 95 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00001501126beb30 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1150 in _loop
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756 in loop_forever
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591 in _thread_main
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015011892cb30 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x0000150119fffb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015011a5ffb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015011abffb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015011b1ffb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015011b7ffb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015011bd7fb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015011c5ffb30 (most recent call first):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 75 in _worker
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x000015011cbf7b30 (most recent call first):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1462 in dequeue
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1513 in _monitor
  File "/usr/local/lib/python3.9/threading.py", line 910 in run
  File "/usr/local/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/local/lib/python3.9/threading.py", line 930 in _bootstrap

Current thread 0x00001501202368b0 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/utils.py", line 57 in __getitem__
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/ssdp_listener.py", line 115 in combined_headers
  File "/usr/src/homeassistant/homeassistant/components/ssdp/__init__.py", line 477 in _ssdp_listener_callback
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/ssdp_listener.py", line 430 in _on_search
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/search.py", line 83 in _async_on_data
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890 in _run_once
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596 in run_forever
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629 in run_until_complete
  File "/usr/src/homeassistant/homeassistant/runner.py", line 121 in run
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 318 in main
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 331 in <module>
  File "/usr/local/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/local/lib/python3.9/runpy.py", line 197 in _run_module_as_main
Fatal Python error: Segmentation fault

Thread 0x0000146f109ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/site-packages/scapy/supersocket.py", line 259 in select
  File "/usr/local/lib/python3.10/site-packages/scapy/sendrecv.py", line 1175 in _run
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f11dffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/src/homeassistant/homeassistant/components/recorder/executor.py", line 17 in _worker_with_shutdown_hook
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f123ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/src/homeassistant/homeassistant/components/recorder/executor.py", line 17 in _worker_with_shutdown_hook
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f129ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/src/homeassistant/homeassistant/components/recorder/executor.py", line 17 in _worker_with_shutdown_hook
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f12fdeb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/src/homeassistant/homeassistant/components/recorder/executor.py", line 17 in _worker_with_shutdown_hook
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f1ddffb30 (most recent call first):
  File "/usr/local/lib/python3.10/threading.py", line 324 in wait
  File "/usr/local/lib/python3.10/queue.py", line 180 in get
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 95 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f21fffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f225ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f22bffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f231ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f237f9b30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f23e24b30 (most recent call first):
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1150 in _loop
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756 in loop_forever
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591 in _thread_main
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f8627fb30 (most recent call first):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 671 in _run_event_loop
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 662 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f891ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f897ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f89dffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f8a3ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f8a9ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f8afffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f8c5fbb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f8c6ffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f8cdffb30 (most recent call first):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x0000146f8d3feb30 (most recent call first):
  File "/usr/local/lib/python3.10/logging/handlers.py", line 1505 in dequeue
  File "/usr/local/lib/python3.10/logging/handlers.py", line 1556 in _monitor
  File "/usr/local/lib/python3.10/threading.py", line 953 in run
  File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap

Current thread 0x0000146f914b0ab0 (most recent call first):
  File "/usr/src/homeassistant/homeassistant/helpers/dispatcher.py", line 105 in async_dispatcher_send
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 611 in webhook_update_sensor_states
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 151 in validate_and_run
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80 in _run
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1896 in _run_once
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 600 in run_forever
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 633 in run_until_complete
  File "/usr/src/homeassistant/homeassistant/runner.py", line 119 in run
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 191 in main
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 203 in <module>
  File "/usr/local/lib/python3.10/runpy.py", line 86 in _run_code
  File "/usr/local/lib/python3.10/runpy.py", line 196 in _run_module_as_main

Extension modules: _cffi_backend, multidict._multidict, yarl._quoting_c, ciso8601, aiohttp._helpers, aiohttp._http_writer, _brotli, aiohttp._http_parser, aiohttp._websocket, cchardet._cchardet, frozenlist._frozenlist, markupsafe._speedups, yaml._yaml, PIL._imaging, simplejson._speedups, sqlalchemy.cimmutabledict, greenlet._greenlet, sqlalchemy.cprocessors, sqlalchemy.cresultproxy, MySQLdb._mysql, dbus_fast.signature, dbus_fast._private.marshaller, dbus_fast.message, dbus_fast._private.unmarshaller, dbus_fast.unpack, dbus_fast.aio.message_reader, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, lxml._elementpath, lxml.etree, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, psutil._psutil_linux, psutil._psutil_posix, av.logging, av._core, av.bytesource, av.buffer, av.audio.format, av.enum, av.error, av.utils, av.option, av.descriptor, av.container.pyio, av.dictionary, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.packet, av.container.input, av.bitstream.filter, av.bitstream.context, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.audio.fifo, av.filter.pad, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.audio.resampler, matplotlib._c_internal_utils, matplotlib._path, kiwisolver._cext, matplotlib._image, psycopg2._psycopg (total: 114)
